---
abstract: "Implementation of a Bogosort (aka 'stupid sort' or 'slowsort')."
author:
  - 'David Oswald <davido[at]cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Acme-Sort-Bogosort
no_index:
  directory:
    - t
    - inc
requires:
  Test::More: 0
  Try::Tiny: 0
  parent: 0
version: 0.05
